apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: no-resource-requests
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: no-resource-requests-webhook
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: no-resource-requests
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: no-resource-requests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: no-resource-requests-webhook
